
version: "3"

vars:
  REGISTRY: scr.tiab.labda.sva.de
  CI_PROJECT_NAME: sthings-frontend
  LOCAL_PORT: 8001
  CONTAINER_PORT: 80
  VUE_APP_API_URL: https://sng.teasle.sthings.tiab.ssc.sva.de

  GIT_COMMIT:
    sh: git log -n 1 --format=%h
  DATE: 
    sh: date +%FT%TZ%z
  MAJOR: 
    sh: yq e '.general.major' .decksman.yaml
  MINOR: 
    sh: yq e '.general.minor' .decksman.yaml
  PATCH: 
    sh: yq e '.general.patch' .decksman.yaml

tasks:
  run:
    desc: Serve dev server
    env:
      PORT: "{{ .LOCAL_PORT }}"
    cmds:
      - npm run serve

  push:
    desc: Commit & push the app
    cmds:
      - git add src/assets/*
      - git add src/components/*
      - git pull
      - |
        echo "Enter COMMIT_MESSAGE:"
        read COMMIT_MESSAGE;
        git commit -am "${COMMIT_MESSAGE} for {{ .MAJOR }}.{{ .MINOR }}.{{ .PATCH }}"
      - git push

  build-container:
    desc: Build & push the container to registry
    cmds:
      #- sudo nerdctl login -u sthings {{ .REGISTRY }}
      - sudo nerdctl build -t {{ .REGISTRY }}/{{ .CI_PROJECT_NAME }}/{{ .CI_PROJECT_NAME }}:{{ .MAJOR }}.{{ .MINOR }}.{{ .PATCH }} . 
      - sudo nerdctl push {{ .REGISTRY }}/{{ .CI_PROJECT_NAME }}/{{ .CI_PROJECT_NAME }}:{{ .MAJOR }}.{{ .MINOR }}.{{ .PATCH }}
  
  run-container:
    desc: Run build build image local
    cmds:
      - sudo nerdctl run -p {{ .CONTAINER_PORT }}:{{ .CONTAINER_PORT }} -e VUE_APP_API_URL={{ .VUE_APP_API_URL }} {{ .REGISTRY }}/{{ .CI_PROJECT_NAME }}/{{ .CI_PROJECT_NAME }}:{{ .MAJOR }}.{{ .MINOR }}.{{ .PATCH }}
