---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: sthings-frontend
  name: sthings-frontend
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: sthings-frontend
  type: NodePort
